# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'
# strategy:
#   matrix:
#     Python36:
#       python.version: '3.6'

variables:
  # カバレッジ計測用
  # ここで指定されたPythonバージョンでカバレッジを計測する
  MAJOR_PYTHON_VERSION: '3.6'

jobs:
- job: test
  strategy:
    matrix:
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: coverage
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(MAJOR_PYTHON_VERSION)'
    displayName: 'Use Python $(MAJOR_PYTHON_VERSION)'
  - script: |
      pip install pytest=6.0.1 pytest-azurepipelines=0.8.0 pytest-cov=2.10.1
      pytest -v --cov --cov_report=xml
#      pytest -v --cov --cov_report=html
    displayName: 'calc coverage'


# stages:
# - stage: test0
#   jobs:
#   - job: test00
#     strategy:
#       matrix:
#         Python36:
#           python.version: '3.6'
# - stage: test1
#   jobs:
#   - job: test10
#     displayName: test1-1
#     steps:
#     - script: echo test1-1
#   - job: test20
#     displayName: test1-2
#     steps:
#     - task: UsePythonVersion@0
#       inputs:
#         versionSpec: '$(python.version)'
#       displayName: 'Use Python $(python.version)'

#     - script: |
#         python -m pip install --upgrade pip
#         pip install -r requirements.txt
#       displayName: 'Install dependencies'

#     - script: |
#         pip install pytest pytest-azurepipelines
#         pytest
#       displayName: 'pytest'

# steps:
# - task: UsePythonVersion@0
#   inputs:
#     versionSpec: '$(python.version)'
#   displayName: 'Use Python $(python.version)'

# - script: |
#     python -m pip install --upgrade pip
#     pip install -r requirements.txt
#   displayName: 'Install dependencies'

# - script: |
#     pip install pytest pytest-azurepipelines
#     pytest
#   displayName: 'pytest'
