# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master
- branch
pool:
  vmImage: 'ubuntu-16.04'

variables:
  # カバレッジ計測用
  # ここで指定されたPythonバージョンでカバレッジを計測する
  MAJOR_PYTHON_VERSION: '3.6'

jobs:
- job: test
  # 将来的にPythonの複数バージョンテストがしたくなった時のためにこの記載にしておく
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
    displayName: 'Use Python $(python.version)'
  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      pip install pytest pytest-azurepipelines
      pytest
    displayName: 'pytest'

- job: coverage
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(MAJOR_PYTHON_VERSION)'
    displayName: 'Use Python $(MAJOR_PYTHON_VERSION)'
  - script: |
      # テスト、カバレッジ表示に必要なツールをインストールして、カバレッジを出力する
      pip install pytest==6.0.1 pytest-azurepipelines==0.8.0 pytest-cov==2.10.1
      pytest --cov -v --cov-report=xml 
    displayName: 'calc coverage'